# Generated by Django 4.2.3 on 2024-05-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0009_remove_tournament_winner_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
