# Generated by Django 4.2.3 on 2024-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0010_user_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
    ]
