# Generated by Django 4.2.3 on 2024-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0011_game_score_player1_game_score_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
